#!/usr/bin/env bash
# display domain and the subdomains based on user input

subdomains=("www" "lb-01" "web-01" "web-02")
func () {
	# check if both arguments are passed
	if [ "$2" ]
	then
		# Use dig to get the IP addresses for each subdomain and format the output
		dig "$2"."$1" | awk '/^;; ANSWER SECTION:$/{getline; sub(/\.$/, "", $1); print "The subdomain "$1" is a "$4" record and points to "$5}'

	
	# check if only the first argument is passed
	elif [ "$1" ]
	then
		# loop through each subdomain
		for subdomain in "${subdomains[@]}"
		do
			# Use dig to get the IP addresses for each subdomain and format the output
			dig "$subdomain"."$1" | awk '/^;; ANSWER SECTION:$/ {getline; sub(/\.$/, "", $1); print "The subdomain "$1" is a "$4" record and points to "$5}'
		done
	else
		echo "Nothing was passed"
		return 0
	fi
	return 0
}
func "$@"
