#!/usr/bin/env bash
# script installs nginx, configures nginx to listen to port 80,
# and adds content to the index page

# remove existing nginx
sudo apt purge -y nginx

# update packages
sudo apt update

# install nginx
sudo apt install -y nginx

# configure nginx to listen to port 80
sudo sed -i 's/^\(listen\s*.*\):[0-9]\+/80/' /etc/nginx/sites-enabled/default

# restart nginx to apply configuration changes
sudo service nginx restart

# modify content of landing page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# add custom header
curl -v -H "X-Served-By: web-02" 0.0.0.0

