#!/usr/bin/env bash
# script installs nginx, configures nginx to listen to port 80,
# and adds content to the index page

# remove existing nginx
sudo apt purge -y nginx

# update packages
sudo apt update

# install nginx
sudo apt install -y nginx

# configure nginx to listen to port 80
sudo sed -i 's/^\(listen\s*.*\):[0-9]\+/80/' /etc/nginx/sites-enabled/default

# add custom header
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# restart nginx to apply configuration changes
sudo service nginx restart
