#!/usr/bin/env bash
# install and configure load balancer version 2.0 stable release

# update package libraries
sudo apt update

# install haproxy 2.0
sudo apt-get -y install haproxy=2.0.\*

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 498655-web-01 100.25.24.173:80 check
    server 498655-web-02 54.237.54.104:80 check
"
# Create a backup for original configurations
sudo cp -a /etc/haproxy/haproxy.cfg{,.backup}

# Add new configurations
echo "$balancer" | sudo tee -a  /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start
