#!/usr/bin/env bash
# Display the content of a file /etc/passwd

# File path
passwd_file="/etc/passwd"

# Check if the file exists
if [ ! -e "$passwd_file" ]
then
    echo "Error: $passwd_file does not exist."
    exit 1
fi

# Read the file line by line
while IFS=":" read -r username _ userid _ _ home_directory _
do
    # Display the required information
    echo "$username:$userid:$home_directory"
done < "$passwd_file"
