#!/usr/bin/env bash
# Display the content of a file /etc/passwd

# File path
passwd_file="/etc/passwd"

# Check if the file exists
if [ ! -e "$passwd_file" ]
then
    echo "Error: $passwd_file does not exist."
    exit 1
fi

# Read the file line by line
while IFS=":" read -r username password userid groupid userinfo home_directory login_shell
do
    # Display the required information
    echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $login_shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < "$passwd_file"
