#!/usr/bin/env bash
#This script displays "Best School" 10 times

num=1

while [ $num -le 20 ]
do
	case $num in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy"
	esac
	echo $num
	((num++))
done
