#!/usr/bin/env bash
# install firewall and set up some rules

# update package libraries
sudo apt update

# install uncomplicated firewall
sudo apt install ufw

# block all incoming traffic
sudo ufw default deny incoming

# allow all outgoing traffic
sudo ufw default allow outgoing

# allow ports
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp

# show added rules
sudo ufw show added

# enable firewall
sudo ufw enable
