#!/usr/bin/env bash
# configure ubuntu server with the following requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

if [ "$EUID" -ne 0 ]
then
	echo "Please run as root"	
exit
fi
cp /etc/hosts /etc/hosts.new

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
