#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.

# replace user www-data with nginx in the config file
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# listen to port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# change file permissions
chmod 644 /etc/nginx/nginx.conf

# kill nginx
pkill nginx

# run nginx as nginx
sudo -u nginx service nginx start
